### ISSUE TITLE
wordpress latest version check broken

### ISSUE THREAD

**Issue by styx-tdo** [richardforth/wp_version_scanner#62]
line 170 should be:
        our $response = `curl -sILk https://wordpress.org/latest | grep -i Content-Disposition`;

**Comment by styx-tdo** [comment]
Hi Richard,
because they enforce https.
styx@osiris:~$ curl -sILk wordpress.org/latest 
HTTP/1.1 301 Moved Permanently
Server: nginx
Date: Sat, 15 Dec 2018 17:04:23 GMT
Content-Type: text/html
Content-Length: 178
Connection: keep-alive
Location: https://wordpress.org/latest

HTTP/2 200 
server: nginx
date: Sat, 15 Dec 2018 17:04:23 GMT
content-type: application/octet-stream
content-length: 10506712
cache-control: private
content-disposition: attachment; filename=wordpress-5.0.1.tar.gz
last-modified: Thu, 13 Dec 2018 02:13:32 GMT
x-frame-options: SAMEORIGIN
content-md5: fb4d3d4da07ded1ece142514dae4b1a4
x-nc: HIT ord 2
accept-ranges: bytes

and that does NOT contain the requested information.

**Comment by styx-tdo** [comment]
i cannot reproduce your result with curl 7.52 or curl 7.62 - both return the header name in lower-case.
the https in the check is just to make it faster - avoiding a 302 redirect.
possibly they use a CDN that has different webservers, depending on where you are.

btw:
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2
Field names are case-insensitive

so, to make this app conform to RFC standards, the matching should be case-insentive.

**Comment by richardforth** [comment]
this is being addressed shortly! sorry
